### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by Opfour** [sqall01/chasr-server#1]
I know this is a gps tracking app and understand how it works, but the question is why would I want to use this program? What purpose does it serve? 🙂

(so not trying to be a smartass, honestly trying to understand)

**Comment by sqall01** [comment]
I do not know if I understand the question? The obvious answer is to track your gps position or the gps position of your devices.

But I guess you want examples: Well you could for example use this to track the position of your car (I wrote an article about it [here](https://h4des.org/blog/index.php?/archives/362-Dude,-where-is-my-car-Android-Edition-Part-2.html)). If you have a small company you could even track your car pool with this in a really cheap way. This even allows you to build a cheap car alarm system. I also know a biker who is using this on his tours so his family knows where he is in case of an accident. I heard from a farmer once that he was interested in such a system to track his tractors in the field.

Personally, my wife and I often use it if we want to meet up in the city or at a town festival and someone knows he will be late and catches up. This way you do not have to meet at a fixed location or phone/message to agree on a meeting point.

There will certainly be other scenarios where it is interesting for someone to track a device and share the position. But these above were just the ones off top of my head.

I hope this answers your questions. I close the issue, but feel free to open it if needed.
